# ========================
# Общие настройки запуска
# ========================
version: "2"
settings:
  run:
    # Проверяем весь проект (./...)
    tests: true
    skip-dirs:
      - migrations       # Игнорируем SQL
      - config           # Игнорируем YAML
    allow-parallel-runners: true

# ========================
# Включенные линтеры
# ========================
  linters:
    enable:
      - govet           # Анализирует код на подозрительные конструкции
      - errcheck        # Проверка необработанных ошибок
      - staticcheck     # Статический анализ - находит баги, упрощает код
      - gosimple        # Упрощение кода
      - ineffassign     # Неиспользуемые присваивания
      - unused          # Неиспользуемые переменные, импорты, функции
      - typecheck       # Проверка типов
      - gofmt           # Проверка форматирования
      - goimports       # Проверка импортов
      - dupl            # Поиск дублированного кода
      - gocyclo         # Проверка сложности функций (if, switch, for, &&, ||)
      - revive          # Анализ стиля кода
      - unparam         # Неиспользуемые параметры
      - prealloc        # Предварительное выделение слайсов, где это нужно
      - gosec           # Поиск уязвимостей безопасности
      - gocritic        # Строгие проверки стиля
      - bodyclose       # Проверка закрытия HTTP body
      - nilerr          # Проверка возврата nil вместо ошибки
      - errorlint       # Проверка оборачивания ошибок
      - misspell        # Орфографические ошибки
      - gocognit        # Когнитивная сложность (альтернатива gocyclo)
      - nilnil          # Запрет возврата (nil, nil)
# ========================
# Настройки отдельных линтеров
# ========================
  linters-settings:
    gocyclo:
      min-complexity: 15   # Допустимая сложность функции
    gocognit:
      min-complexity: 20  # Когнитивная сложность
    dupl:
      threshold: 150       # Минимальное количество повторяющихся токенов
    revive:
      ignore-generated-header: true
      severity: warning
      rules:
        - name: var-naming
        - name: indent-error-flow
        - name: empty-lines
        - name: unused-parameter
        - name: exported
          severity: warning
        - name: error-strings  # Ошибки с маленькой буквы
        - name: error-return   # error всегда последний параметр
        - name: context-as-argument  # context первым параметром
    goimports:
      local-prefixes: github.com/KungurtsevNII/team-board-back
    govet:
      enable-all: true
      disable:
        - shadow  # Слишком много ложных срабатываний

    errcheck:
      check-type-assertions: true  # 🆕 Проверка type assertion
      check-blank: true            # 🆕 Проверка _ = err

    gosec:
      excludes:
        - G104  # Unhandled errors (дублирует errcheck)

    staticcheck:
        checks: [ "all" ]

# ========================
# Вывод результатов
# ========================
  issues:
    exclude-use-default: false
    exclude-rules:
      # Игнорировать длинные строки в тестах
      - path: _test\.go
        linters:
          - lll
          - dupl
    max-issues-per-linter: 0
    max-same-issues: 0

# ========================
# Формат вывода
# ========================
  output:
    formats:
      - format: colored-line-number
        path: stdout
    print-issued-lines: true
    print-linter-name: true
    uniq-by-line: true
    sort-results: true
