// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/KungurtsevNII/team-board-back/src/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// CheckBoard provides a mock function with given fields: ctx, id
func (_m *Repo) CheckBoard(ctx context.Context, id string) bool {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CheckBoard")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CreateColumn provides a mock function with given fields: ctx, column
func (_m *Repo) CreateColumn(ctx context.Context, column *domain.Column) error {
	ret := _m.Called(ctx, column)

	if len(ret) == 0 {
		panic("no return value specified for CreateColumn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Column) error); ok {
		r0 = rf(ctx, column)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLastOrderNumColumn provides a mock function with given fields: ctx, boardID
func (_m *Repo) GetLastOrderNumColumn(ctx context.Context, boardID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, boardID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastOrderNumColumn")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, boardID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, boardID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, boardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
