// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateBoardRequest defines model for CreateBoardRequest.
type CreateBoardRequest struct {
	// Name Название доски
	Name string `json:"name"`

	// ShrortName Короткое имя доски (2-10 символов, только буквы, цифры, дефисы и подчеркивания)
	ShrortName string `json:"shrort_name"`
}

// CreateBoardResponse defines model for CreateBoardResponse.
type CreateBoardResponse struct {
	// Id UUID созданной доски
	Id *openapi_types.UUID `json:"id,omitempty"`
}

// CreateColumnRequest defines model for CreateColumnRequest.
type CreateColumnRequest struct {
	// Name Название колонки
	Name string `json:"name"`
}

// CreateColumnResponse defines model for CreateColumnResponse.
type CreateColumnResponse struct {
	// BoardId UUID доски, к которой принадлежит колонка
	BoardId *openapi_types.UUID `json:"board_id,omitempty"`

	// CreatedAt Дата и время создания колонки
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DeletedAt Дата и время удаления колонки (null, если не удалена)
	DeletedAt *time.Time `json:"deleted_at"`

	// Id UUID созданной колонки
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Name Название колонки
	Name *string `json:"name,omitempty"`

	// OrderNum Порядковый номер колонки на доске
	OrderNum *int64 `json:"order_num,omitempty"`

	// UpdatedAt Дата и время последнего обновления колонки
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code HTTP код ошибки
		Code int `json:"code"`

		// Message Описание ошибки
		Message string `json:"message"`
	} `json:"error"`
}

// CreateBoardJSONRequestBody defines body for CreateBoard for application/json ContentType.
type CreateBoardJSONRequestBody = CreateBoardRequest

// CreateColumnJSONRequestBody defines body for CreateColumn for application/json ContentType.
type CreateColumnJSONRequestBody = CreateColumnRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Проверка здоровья сервиса
	// (GET /healthcheck)
	Healthcheck(c *gin.Context)
	// Создать новую доску
	// (POST /v1/boards)
	CreateBoard(c *gin.Context)
	// Создать новую колонку
	// (POST /v1/boards/{board_id}/columns)
	CreateColumn(c *gin.Context, boardId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Healthcheck operation middleware
func (siw *ServerInterfaceWrapper) Healthcheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthcheck(c)
}

// CreateBoard operation middleware
func (siw *ServerInterfaceWrapper) CreateBoard(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateBoard(c)
}

// CreateColumn operation middleware
func (siw *ServerInterfaceWrapper) CreateColumn(c *gin.Context) {

	var err error

	// ------------- Path parameter "board_id" -------------
	var boardId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "board_id", c.Param("board_id"), &boardId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter board_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateColumn(c, boardId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthcheck", wrapper.Healthcheck)
	router.POST(options.BaseURL+"/v1/boards", wrapper.CreateBoard)
	router.POST(options.BaseURL+"/v1/boards/:board_id/columns", wrapper.CreateColumn)
}
